[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# This section sets the Content Security Policy for your entire site.
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://alcdn.msauth.net browser.events.data.microsoft.com;
      connect-src 'self' https://jfgytmiglggzirfohwug.supabase.co wss://*.supabase.co https://login.microsoftonline.com https://graph.microsoft.com https://browser.events.data.microsoft.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data:;
      wasm-src 'self' 'unsafe-eval';
    """
